INSERT INTO Manufactures VALUES

 (N'NXB Kim Đồng', N'nxb-kim-dong.png', N'nxb-kim-dong-banner.jpg', N'Nhà xuất bản Kim Đồng trực thuộc Trung ương Đoàn TNCS Hồ Chí Minh là Nhà xuất bản tổng hợp có chức năng xuất bản sách và văn hóa phẩm phục vụ thiếu nhi và các bậc phụ huynh trong cả nước, quảng bá và giới thiệu văn hóa Việt Nam ra thế giới. Nhà xuất bản có nhiệm vụ tổ chức bản thảo, biên soạn, biên dịch, xuất bản và phát hành các xuất bản phẩm có nội dung: giáo dục truyền thống dân tộc, giáo dục về tri thức, kiến thức… trên các lĩnh vực văn học, nghệ thuật, khoa học', CAST(N'2023-09-21T20:08:21.840' AS DateTime), 1, NULL, 0, NULL, 0),
 (N'Thái Hà', N'thai-ha.jpg', N'thai-ha-banner.jpg', N'Thái Hà Books mong muốn mang tri thức trong những cuốn sách ở khắp nơi trên thế giới đến với độc giả Việt Nam. Những cuốn sách có giá trị, có tính ứng dụng và thực tiễn cao của Thái Hà Books sẽ làm cho cuộc sống tươi đẹp hơn, phong phú hơn. Trong tương lai, với xu thế hội nhập toàn cầu, Thái Hà Books mong muốn trở thành con chim đầu đàn đi ra biển lớn.', CAST(N'2023-09-21T20:10:50.670' AS DateTime), 1, NULL, 0, NULL, 0),
 (N'FIRST NEWS', N'first-new.jpg', N'first-new-banner.png', N'Được thành lập vào ngày 10/12/1994 với tên gọi ban đầu là “Ban Biên Dịch First News”, trải qua 25 năm luôn nỗ lực và sáng tạo, đến nay First News – Trí Việt đã khẳng định được vị thế cũng như uy tín của mình trong lòng bạn đọc, không những bởi sự phong phú của những dòng sách giá trị trên thế giới mà First News đã nhạy bén chuyển ngữ phục vụ người Việt Nam, mà còn vì chất lượng cũng như sự chỉn chu trong từng quyển sách mà First News mong muốn mang đến cho bạn đọc.', CAST(N'2023-09-22T05:32:29.543' AS DateTime), 1, NULL, 0, NULL, 0),
 (N'AZ Việt Nam', N'az-viet-nam.jpg', N'az-viet-nam-banner.jpg', N'Khởi nguồn của AZ Việt Nam ngày nay là Công ty TNHH Trung tâm Sách và Thiết bị Thư viện, với hoạt động đầu tiên là cung cấp sách, trang thiết bị, văn hóa phẩm cho các thư viện và trung tâm sách trên cả nước. Từ cuối năm 2010 đến nay, chúng tôi đã không ngừng nỗ lực khai phá và phát triển các dòng sản phẩm mới với 8 thương hiệu uy tín.', CAST(N'2023-09-22T05:35:32.713' AS DateTime), 1, NULL, 0, NULL, 0),
 (N'IPM', N'ipm.jpg', N'ipm-sach-banner.jpg', N'Công ty Cổ phần Xuất bản và Truyền thông IPM được thành lập tháng 02 năm 2004 bới một nhóm sáng lập viên trẻ tuổi, nhiệt tình và năng động và có nhiều năm kinh nghiệm hoạt động trong lĩnh vực xuất bản Việt Nam. Ngay sau khi Việt Nam chính thức tham gia công ước Berne (Công ước quốc tế về bảo hộ các tác phẩm văn học nghệ thuật) vào ngày 24/10/2004, IPM là một trong số ít các công ty Việt Nam đi tiên phong trong việc tìm kiếm, khai thác và mua bản quyền sách nước ngoài.', CAST(N'2023-09-22T05:36:28.887' AS DateTime), 2, NULL, 0, NULL, 0),	   
 (N'Amak Books', N'amak-book.png', N'amak-book-banner.png', N'Amak Books, hiện đã trở thành một nhãn sách độc lập thuộc về công ty X.Y.Z. Chúng tôi tự hào là một trong những người tiên phong thương hiệu trong lĩnh vực chính sách bản quyền tại Việt Nam. Qua nhiều năm, với những nỗ lực và sự đóng góp của đội ngũ nhân viên của chúng tôi, sự năng động và nhiệt tình của các cộng tác viên, AMAK BOOKS đã trở thành một thương hiệu sách đáng tin cậy với danh tiếng tốt cho tất cả các đối tác bên trong và ngoài nước.', CAST(N'2023-09-22T05:59:01.767' AS DateTime), 4, NULL, 0, NULL, 0), 
 (N'NXB Trẻ', N'nxb-tre.jpg', N'nxb-tre-banner.jpg', N'Sau gần năm năm hoạt động với nhiều nỗ lực và hiệu quả, ngày 3-2-1986, NXB Măng Non được UBND TP.HCM ký quyết định đổi tên thành NXB Trẻ với chức năng và nhiệm vụ được mở rộng là đơn vị xuất bản dành cho thanh thiếu nhi thành phố và khu vực Nam bộ.', CAST(N'2023-09-22T05:59:54.977' AS DateTime), 3, NULL, 0, NULL, 0),
 (N'Alpha Books', N'alpha-book.png', N'alpha-book-banner.jpg', N'Công ty cổ phần Sách Alpha (Alpha Books Joint-Stock Company – gọi tắt là Alpha Books) do một nhóm trí thức trẻ thành lập ở Hà Nội năm 2005 với niềm tin: Tri thức là Sức mạnh. Thông qua việc giới thiệu các tác phẩm có giá trị của thế giới, Alpha Books mong muốn trở thành nhịp cầu nối nguồn tri thức nhân loại với dân tộc Việt Nam.', CAST(N'2023-09-22T06:01:33.803' AS DateTime), 2, NULL, 0, NULL, 0),
 (N'SkyBooks', N'sky-book.png', N'sky-book-banner.jpg', N'Thương hiệu sách Skybooks là địa chỉ tin cậy cho các tác giả trẻ Việt Nam gửi gắm tác phẩm của mình. Với khẩu hiệu “Tôi trẻ, tôi đam mê”, chúng tôi luôn nỗ lực để mang đến cho độc giả những tác phẩm chất lượng từ các tác giả trẻ nổi bật cũng như giúp đỡ, tạo điều kiện cho các cây bút trẻ được đông đảo độc giả biết đến. Hãy để Skybooks trở thành người đưa đứa con tinh thần của bạn đến với công chúng!', CAST(N'2023-09-22T06:01:33.803' AS DateTime), 1, NULL, 0, NULL, 0),
 (N'Nhã Nam', N'nha-nam.jpg', N'nha-nam-banner.png', N'Tháng 2 năm 2005, Nhã Nam, tên đầy đủ là Công ty Cổ phần Văn hóa và Truyền thông Nhã Nam đã gia nhập thị trường sách. Tác phẩm "Balzac và cô bé thợ may Trung hoa" của Đới Tư Kiệt là cuốn sách đầu tiên được những người sáng lập Nhã Nam xuất bản cả trước khi công ty ra đời. Ngay lập tức từ cuốn sách đầu tiên, độc giả đã dành sự quan tâm và yêu mến cho một thương hiệu sách mới mẻ mang trong mình khát vọng góp phần tạo lập diện mạo mới cho xuất bản văn học tại Việt Nam.', CAST(N'2023-09-22T06:01:33.803' AS DateTime), 4, NULL, 0, NULL, 0),
 (N'NXB Tổng Hợp', N'nxb-tong-hop.jpg', N'nxb-tong-hop-banner.png', N'Nhà xuất bản Tổng hợp thành phố Hồ Chí Minh là cơ quan chính trị – tư tưởng – văn hóa của Đảng bộ và nhân dân thành phố Hồ Chí Minh được thành lập từ năm 1977 xuất bản hàng ngàn tựa sách gồm nhiều thể loại về chính trị, lịch sử, văn hóa, kinh tế, pháp luật, khoa học - kỹ thuật, từ điển, ngoại ngữ', CAST(N'2023-09-22T06:01:33.803' AS DateTime), 5, NULL, 0, NULL, 0);
 

select * from Manufactures